### ISSUE TITLE
Function 2: heatmap

### ISSUE THREAD

**Issue by showcy** [UBC-MDS/collinearity_tool#12]
A function for creating the correlation heatmap.

**Comment by showcy** [comment]
Input is the data frame now. I would calculate the correlation at first. Then change it by calling the return from Nick's corr_matrix function.

**Comment by showcy** [comment]
Instead of using seaborn. I decide to code it from scratch using Altair.

**Comment by katerinkus** [comment]
Hey! I think you are missing` from collinearity_tool.collinearity_tool import <your_function_name>` from the testing file.

**Comment by showcy** [comment]
Done

**Comment by showcy** [comment]
Just a notes for grading, there is no exception handling for my function because the process of input is done in Nick’s corr_matrix function.
