### ISSUE TITLE
Function 4: Identification

### ISSUE THREAD

**Issue by katerinkus** [UBC-MDS/collinearity_tool#20]
This issue pertains to the function #4 which determines which values to eliminate based on VIF and Pearson coefficient scores.

**Comment by katerinkus** [comment]
Created the function and its code. It will be merged soon. Progress can be seen here: src/collinearity_tool/collinearity_tool.py, branch col_identify ([link](https://github.com/UBC-MDS/collinearity_tool/blob/c8fe41dd9085bac17f03c64e9b55a6460dea0161/src/collinearity_tool/collinearity_tool.py)).

**Comment by showcy** [comment]
During test, I found when there is no problem is x = [‘cyl’, ‘cty’] but there is error for x = [‘displ’, ‘year’] when y = 'hwy' and running cl.col_identify(data, x, y). 
The error is:
`Expected a 1D array, got an array with shape (0, 4)`

If there should be constraints to what x is chosen, a error check might be needed.
