### ISSUE TITLE
Function 3: VIF

### ISSUE THREAD

**Issue by Anahita97** [UBC-MDS/collinearity_tool#28]
This is the issue for the 3rd function. This function will return a data frame and a bar plot containing Variance Inflation Factor (VIF) for each explanatory variable in a linear multiple regression model.

**Comment by Anahita97** [comment]
There will a threshold added to the function, so the threshold as to which variables are identified as VIFs can be determined by the user.

**Comment by Anahita97** [comment]
Would be a good idea to include an optional intercept argument in the function. Since often times, the intercept has very high VIF scores.

**Comment by showcy** [comment]
Done for now.
