### ISSUE TITLE
Update test file to include pytest test functions

### ISSUE THREAD

**Issue by nickmao1994** [UBC-MDS/collinearity_tool#37]
Add pytest test funtions for every functions

**Comment by showcy** [comment]
Since my input was called by the Nick's function directly. It seems there is no test needed in the heat map function.

**Comment by katerinkus** [comment]
I think this issue is complete?

**Comment by nickmao1994** [comment]
Ana mentioned about using a specific function to write test code, but after checking the requirements in assignments and how others are doing, I think we are good with our current tests.
